# Generated by Django 5.2.8 on 2025-12-10 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=200, verbose_name='Generic Name')),
                ('brand_name', models.CharField(blank=True, max_length=200, verbose_name='Brand Name')),
                ('batch_number', models.CharField(max_length=100, verbose_name='Batch Number')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity in Stock')),
                ('tablets_per_pack', models.PositiveIntegerField(default=10, verbose_name='Tablets per Pack')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost Price')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated as 1.5x cost price', max_digits=10, verbose_name='Selling Price')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Manufacturer')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Category')),
                ('storage_conditions', models.CharField(blank=True, max_length=200, verbose_name='Storage Conditions')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='The_Tally.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Drug',
                'verbose_name_plural': 'Drugs',
                'ordering': ['generic_name', 'brand_name'],
            },
        ),
    ]
