# Generated by Django 5.2.8 on 2025-12-10 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Tally', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='drug',
            old_name='batch_number',
            new_name='batch',
        ),
        migrations.RenameField(
            model_name='drug',
            old_name='expiry_date',
            new_name='expiry',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='storage_conditions',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='tablets_per_pack',
        ),
        migrations.AddField(
            model_name='drug',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description/Strength'),
        ),
        migrations.AddField(
            model_name='drug',
            name='dosage',
            field=models.CharField(choices=[('tab', 'Tablet'), ('spr', 'Spray'), ('kit', 'Kit'), ('cap', 'Capsule'), ('syr', 'Syrup'), ('inj', 'Injection'), ('cre', 'Cream'), ('oin', 'Ointment'), ('oth', 'Other')], default='tab', max_length=10, verbose_name='Dosage Form'),
        ),
        migrations.AddField(
            model_name='drug',
            name='drug_type',
            field=models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale')], default='retail', max_length=20, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='drug',
            name='is_dead_stock',
            field=models.BooleanField(default=False, verbose_name='Dead Stock'),
        ),
        migrations.AddField(
            model_name='drug',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Storage Location'),
        ),
        migrations.AddField(
            model_name='drug',
            name='min_qty',
            field=models.IntegerField(default=10, verbose_name='Minimum Quantity'),
        ),
        migrations.AddField(
            model_name='drug',
            name='stock_qty',
            field=models.IntegerField(default=0, verbose_name='Stock Quantity'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='brand_name',
            field=models.CharField(max_length=200, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Cost Price'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drug',
            name='generic_name',
            field=models.CharField(max_length=500, verbose_name='Generic Name'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Selling Price'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='The_Tally.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='The_Tally.category', verbose_name='Category'),
        ),
    ]
